### ISSUE TITLE
sentence perplexity

### ISSUE THREAD

**Issue by NNNNNaaaaa** [Ubiqus/tf_rnnlm#2]
Hello,  when I run the loglikes.py to calculate the perplexity of every sentence, it is very strange that the longer sentence tend to have low perplexity.

**Comment by pltrdy** [comment]
Could you please provide an example to reproduce?

**Comment by NNNNNaaaaa** [comment]
I use the small model with num_step =0, the total vocabulary is 1470 and there are three million sentences in train. Like the following examples,  sentence + perplexity (produced by loglikes.py) in each line and these sentences are from the test, where the perplexity is only 1.6 (produced by test.py). 
党湾 	 22759.560844
开明广场 	 1790.367528
天津东城区 	 448.055858
中石化加油站 	 70.163558
北京市海淀区北三环中路77号 	 65.219993

**Comment by pltrdy** [comment]
In fact, the reported perplexity the word perplexity i.e. it is divided by the sequence length (number of word). Therefore, the reported perplexity does not really depend on the lenght.
