### ISSUE TITLE
dataset problem

### ISSUE THREAD

**Issue by 0uO** [Ubiqus/tf_rnnlm#4]
Hi, your code is clear and useful. but in dataset.py, line 138
 `l = min(80, len(s))`
should it be 
`l = min(max_len, len(s))` ?

and is there an interface for calculate log probability of a batch of sentences? I did't find it.

**Comment by pltrdy** [comment]
Hi,

1) That's correct, `max_len` should be used instead of 80.
2) I think <https://github.com/Ubiqus/tf_rnnlm/blob/master/loglikes.py> is what you want.

**Comment by 0uO** [comment]
Thank you!
